// Turns dashboard/openapi.json, the snapshot of the API's own document, into src/api/schema.ts
// (ADR-031). OpenApiSnapshotTest keeps the snapshot equal to what the API serves, and CI re-runs
// this and fails if the committed output differs, so the dashboard's types cannot drift from the
// API's.
//
//   npm run api:types
//
// It understands the subset of OpenAPI 3.1 the API's document uses and throws on anything else,
// naming where, rather than guessing. Operations are generated for /api/** only: those are the
// ones the dashboard's client can call, with the dashboard's token.

import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

/** Keywords that constrain or describe a value without changing its TypeScript type. */
const DESCRIPTIVE = new Set([
  "description",
  "example",
  "format",
  "default",
  "minLength",
  "maxLength",
  "minimum",
  "maximum",
  "minItems",
  "maxItems",
  "pattern",
]);

const METHODS = ["get", "put", "post", "delete", "patch"] as const;

export class UnsupportedSchema extends Error {}

export function generate(document: Json): string {
  const doc = object(document, "the document");
  const version = doc.openapi;
  if (typeof version !== "string" || !version.startsWith("3.1.")) {
    throw new UnsupportedSchema(`OpenAPI ${String(version)} is not 3.1`);
  }
  const components = object(object(doc.components ?? {}, "components").schemas ?? {}, "schemas");
  const out: string[] = [
    "// Generated by scripts/generate-api-types.ts from openapi.json. Do not edit: change the API,",
    "// regenerate the snapshot, then run npm run api:types (ADR-031).",
    "",
  ];

  for (const name of Object.keys(components).sort()) {
    const schema = object(components[name] ?? null, `schemas.${name}`);
    out.push(...comment(schema, ""));
    if (isObjectSchema(schema) && schema.properties !== undefined) {
      out.push(`export interface ${identifier(name)} ${objectType(schema, `schemas.${name}`, "")}`, "");
    } else {
      out.push(`export type ${identifier(name)} = ${type(schema, `schemas.${name}`, "")};`, "");
    }
  }

  out.push("/** Every /api/** operation, by method and path template. */", "export interface Operations {");
  const paths = object(doc.paths ?? {}, "paths");
  const operations: string[] = [];
  for (const path of Object.keys(paths)) {
    if (!path.startsWith("/api/")) {
      continue;
    }
    const item = object(paths[path] ?? null, `paths.${path}`);
    for (const key of Object.keys(item)) {
      if (!(METHODS as readonly string[]).includes(key)) {
        throw new UnsupportedSchema(`paths.${path}.${key} is not an operation this generator reads`);
      }
    }
    for (const method of METHODS) {
      const op = item[method];
      if (op !== undefined) {
        operations.push(operation(method, path, object(op, `paths.${path}.${method}`)));
      }
    }
  }
  out.push(...operations.sort().flatMap((entry) => entry.split("\n")), "}", "");
  return out.join("\n");
}

function operation(method: string, path: string, op: JsonObject): string {
  const where = `${method.toUpperCase()} ${path}`;
  const params: string[] = [];
  for (const [i, raw] of array(op.parameters ?? [], `${where} parameters`).entries()) {
    const parameter = object(raw, `${where} parameters[${i}]`);
    const name = parameter.name;
    if (typeof name !== "string") {
      throw new UnsupportedSchema(`${where} parameters[${i}] has no name`);
    }
    if (parameter.in !== "path" && parameter.in !== "query") {
      throw new UnsupportedSchema(`${where} parameter ${name} is in ${String(parameter.in)}`);
    }
    const optional = parameter.required === true ? "" : "?";
    const schema = object(parameter.schema ?? null, `${where} parameter ${name}`);
    params.push(`${property(name)}${optional}: ${type(schema, `${where} parameter ${name}`, "      ")}`);
  }

  let body = "never";
  if (op.requestBody !== undefined) {
    const requestBody = object(op.requestBody, `${where} requestBody`);
    body = type(content(requestBody, `${where} requestBody`), `${where} requestBody`, "      ");
  }

  const responses = object(op.responses ?? null, `${where} responses`);
  const success = Object.keys(responses).filter((status) => /^2\d\d$/.test(status));
  if (success.length !== 1) {
    throw new UnsupportedSchema(`${where} documents ${success.length} success responses, not one`);
  }
  const status = success[0] as string;
  const response = object(responses[status] ?? null, `${where} ${status}`);
  const result =
    response.content === undefined ? "void" : type(content(response, `${where} ${status}`), `${where} ${status}`, "      ");

  return [
    `  ${JSON.stringify(where)}: {`,
    `    params: {${params.length === 0 ? "" : ` ${params.join("; ")} `}};`,
    `    body: ${body};`,
    `    response: ${result};`,
    `  };`,
  ].join("\n");
}

/** The schema of an application/json body, the only kind the API sends or takes. */
function content(holder: JsonObject, where: string): JsonObject {
  const media = object(holder.content ?? null, `${where} content`);
  const types = Object.keys(media);
  if (types.length !== 1 || types[0] !== "application/json") {
    throw new UnsupportedSchema(`${where} is ${types.join(", ")}, not application/json alone`);
  }
  return object(object(media["application/json"] ?? null, where).schema ?? null, `${where} schema`);
}

function type(schema: JsonObject, where: string, indent: string): string {
  for (const keyword of Object.keys(schema)) {
    if (
      !DESCRIPTIVE.has(keyword) &&
      !["type", "$ref", "enum", "items", "properties", "required", "additionalProperties"].includes(keyword)
    ) {
      throw new UnsupportedSchema(`${where} uses ${keyword}`);
    }
  }
  if (schema.$ref !== undefined) {
    const ref = schema.$ref;
    if (typeof ref !== "string" || !ref.startsWith("#/components/schemas/")) {
      throw new UnsupportedSchema(`${where} refers to ${String(ref)}`);
    }
    return identifier(ref.slice("#/components/schemas/".length));
  }
  if (Object.keys(schema).every((keyword) => DESCRIPTIVE.has(keyword))) {
    return "unknown";
  }

  const declared = schema.type;
  const types = Array.isArray(declared) ? declared : [declared];
  const nullable = types.includes("null");
  const rest = types.filter((t) => t !== "null");
  if (rest.length !== 1) {
    throw new UnsupportedSchema(`${where} has type ${JSON.stringify(declared)}`);
  }
  let base: string;
  switch (rest[0]) {
    case "string":
      base =
        schema.enum === undefined
          ? "string"
          : array(schema.enum, `${where} enum`)
              .map((value) => {
                if (typeof value !== "string") {
                  throw new UnsupportedSchema(`${where} enum holds ${JSON.stringify(value)}`);
                }
                return JSON.stringify(value);
              })
              .join(" | ");
      break;
    case "integer":
    case "number":
      base = "number";
      break;
    case "boolean":
      base = "boolean";
      break;
    case "array": {
      const items = type(object(schema.items ?? null, `${where} items`), `${where} items`, indent);
      base = /^[\w.]+$/.test(items) ? `${items}[]` : `Array<${items}>`;
      break;
    }
    case "object":
      base = objectType(schema, where, indent);
      break;
    default:
      throw new UnsupportedSchema(`${where} has type ${JSON.stringify(declared)}`);
  }
  if (schema.enum !== undefined && rest[0] !== "string") {
    throw new UnsupportedSchema(`${where} is an enum of ${String(rest[0])}`);
  }
  return nullable ? `${base} | null` : base;
}

function objectType(schema: JsonObject, where: string, indent: string): string {
  const properties = object(schema.properties ?? {}, `${where} properties`);
  const required = new Set(array(schema.required ?? [], `${where} required`));
  const extra = schema.additionalProperties;
  const names = Object.keys(properties);
  if (names.length === 0) {
    if (extra === undefined) {
      throw new UnsupportedSchema(`${where} is an object with neither properties nor additionalProperties`);
    }
    return `Record<string, ${type(object(extra, `${where} additionalProperties`), `${where} additionalProperties`, indent)}>`;
  }
  if (extra !== undefined) {
    throw new UnsupportedSchema(`${where} has both properties and additionalProperties`);
  }
  for (const name of required) {
    if (typeof name !== "string" || !names.includes(name)) {
      throw new UnsupportedSchema(`${where} requires ${String(name)}, which it does not define`);
    }
  }
  const inner = `${indent}  `;
  const lines = ["{"];
  for (const name of names) {
    const property_ = object(properties[name] ?? null, `${where}.${name}`);
    lines.push(...comment(property_, inner));
    const optional = required.has(name) ? "" : "?";
    lines.push(`${inner}${property(name)}${optional}: ${type(property_, `${where}.${name}`, inner)};`);
  }
  lines.push(`${indent}}`);
  return lines.join("\n");
}

function comment(schema: JsonObject, indent: string): string[] {
  const description = schema.description;
  if (typeof description !== "string" || description === "") {
    return [];
  }
  return [`${indent}/** ${description.replaceAll("*/", "*\\/")} */`];
}

function identifier(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new UnsupportedSchema(`schema name ${name} is not an identifier`);
  }
  return name;
}

function property(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function isObjectSchema(schema: JsonObject): boolean {
  return schema.type === "object";
}

function object(value: Json | undefined, where: string): JsonObject {
  if (value === null || value === undefined || typeof value !== "object" || Array.isArray(value)) {
    throw new UnsupportedSchema(`${where} is not an object`);
  }
  return value;
}

function array(value: Json, where: string): Json[] {
  if (!Array.isArray(value)) {
    throw new UnsupportedSchema(`${where} is not an array`);
  }
  return value;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const [input, output] = process.argv.slice(2);
  if (input === undefined || output === undefined) {
    console.error("usage: generate-api-types.ts <openapi.json> <schema.ts>");
    process.exit(2);
  }
  writeFileSync(output, generate(JSON.parse(readFileSync(input, "utf8")) as Json), "utf8");
  console.log(`Wrote ${output}`);
}
