// Generated by scripts/generate-api-types.ts from openapi.json. Do not edit: change the API,
// regenerate the snapshot, then run npm run api:types (ADR-031).

export interface AccessTokenResponse {
  /** Send as `Authorization: Bearer <accessToken>` on `/api/**` */
  accessToken: string;
  tokenType: string;
  expiresAt: string;
}

export interface AccountResponse {
  id: string;
  email: string;
  displayName: string | null;
  createdAt: string;
}

export interface Actor {
  email: string;
  displayName: string | null;
}

export interface ApiKeyResponse {
  id: string;
  name: string;
  type: "server" | "client";
  /** Enough to tell keys apart; not secret */
  prefix: string;
  createdAt: string;
  /** Accurate to about a minute */
  lastUsedAt: string | null;
  revokedAt: string | null;
}

export interface AuditEntryResponse {
  id: string;
  createdAt: string;
  /** From the fixed vocabulary in DATABASE.md */
  action: string;
  actor: Actor;
  /** The environment's key; null when the change was not to one environment. A deleted environment keeps the key it had */
  environment: string | null;
  /** Whether the environment has been deleted since */
  environmentDeleted: boolean;
  /** The flag's key; null when the change was not to one flag */
  flag: string | null;
  /** The state before, as recorded; null for a creation. A rollout is recorded as stored, in basis points under rolloutBasisPoints (ADR-030) */
  previousValue: Record<string, unknown> | null;
  /** The state after, as recorded; null for a deletion */
  newValue: Record<string, unknown> | null;
}

export interface AuditPageResponse {
  /** Newest first */
  entries: AuditEntryResponse[];
  /** Pass as `before` for the next page; null when this page is the last */
  next: string | null;
}

export interface Context {
  key?: string | null;
  attributes?: Record<string, unknown> | null;
}

export interface CreateEnvironmentRequest {
  /** Unique within the project */
  key: string;
  name: string;
}

export interface CreateFlagRequest {
  /** Unique in the project, archived flags included; can never change */
  key: string;
  name: string;
  description?: string | null;
  /** Whether client keys may read it. Defaults to false: browser keys are public */
  clientSideVisible?: boolean;
}

export interface CreateProjectRequest {
  /** Unique across Flaglane; immutable */
  key: string;
  name: string;
}

export interface EnvironmentResponse {
  key: string;
  name: string;
  createdAt: string;
}

export interface EvaluateRequest {
  /** Who to evaluate for. Optional: without it, evaluation is anonymous */
  context?: Context;
  /** The flags to evaluate, each with the value the caller has decided is safe */
  flags: FlagRequest[];
}

export interface EvaluateResponse {
  environment: string;
  /** The ruleset_version the answers were computed from */
  version: number;
  results: Record<string, Result>;
}

export interface FlagConfigResponse {
  flagKey: string;
  environment: string;
  enabled: boolean;
  /** Always false in v0.x (ADR-009) */
  offValue: boolean;
  fallthroughValue: boolean;
  rolloutPercentage: number;
  rolloutSalt: string;
  updatedAt: string;
}

export interface FlagRequest {
  key: string;
  fallback: boolean;
}

export interface FlagResponse {
  key: string;
  name: string;
  description: string | null;
  clientSideVisible: boolean;
  /** Set while the flag is archived */
  archivedAt: string | null;
  createdAt: string;
}

export interface IssueApiKeyRequest {
  name: string;
  /** `server` reads every flag; `client` reads client-side-visible flags only, with no user overrides */
  type: "server" | "client";
}

export interface IssuedApiKeyResponse {
  id: string;
  name: string;
  type: "server" | "client";
  prefix: string;
  createdAt: string;
  /** The key. Shown once and never again */
  key: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface OverrideRequest {
  userKey: string;
  value: boolean;
}

export interface OverridesResponse {
  overrides: OverrideRequest[];
}

export interface ProblemDetail {
  type?: string;
  title?: string | null;
  status?: number;
  detail?: string | null;
  instance?: string | null;
  properties?: Record<string, unknown> | null;
}

export interface ProjectResponse {
  key: string;
  name: string;
  createdAt: string;
}

export interface RegisterRequest {
  /** Stored lower-cased; must be unused */
  email: string;
  /** At least 15 characters and at most 72 bytes of UTF-8, the most bcrypt reads */
  password?: string;
  displayName?: string | null;
}

export interface ReplaceOverridesRequest {
  /** An empty list removes every override (ADR-023: at most 1,000). Overrides do not apply to client keys, on either serving path (FR-KEY-008) */
  overrides: OverrideRequest[];
}

export interface ReplaceRulesRequest {
  /** In priority order. An empty list removes every rule (ADR-023: at most 100) */
  rules: RuleRequest[];
}

export interface Result {
  value: boolean;
  reason: "OFF" | "OVERRIDE" | "RULE_MATCH" | "ROLLOUT" | "FALLTHROUGH" | "FLAG_NOT_FOUND" | "ERROR";
}

export interface RuleRequest {
  attribute: string;
  operator: "EQUALS" | "NOT_EQUALS" | "IN" | "NOT_IN" | "CONTAINS" | "STARTS_WITH" | "ENDS_WITH";
  /** Strings, numbers or booleans. Exactly one for EQUALS, NOT_EQUALS, CONTAINS, STARTS_WITH and ENDS_WITH, the last three strings only; one or more of one type for IN and NOT_IN (ADR-019) */
  matchValues: unknown[];
  /** What the flag evaluates to when the rule matches */
  resultValue: boolean;
}

export interface RulesResponse {
  rules: RuleRequest[];
}

export interface UpdateFlagConfigRequest {
  /** The kill switch. Disabled returns false to everyone */
  enabled?: boolean | null;
  /** Returned when the flag is enabled and nothing else matched. While true, the rollout has no effect: everyone it does not reach gets true anyway */
  fallthroughValue?: boolean | null;
  /** Whole percent of users, stored as basis points (ADR-011) */
  rolloutPercentage?: number | null;
  /** Changing the salt re-buckets every user of this flag: who has it at a given percentage changes. Give flags the same salt to roll them out to the same users (ADR-010) */
  rolloutSalt?: string | null;
}

export interface UpdateFlagRequest {
  name?: string | null;
  /** Empty clears it */
  description?: string | null;
  clientSideVisible?: boolean | null;
}

/** Every /api/** operation, by method and path template. */
export interface Operations {
  "DELETE /api/projects/{projectKey}/environments/{envKey}": {
    params: { projectKey: string; envKey: string };
    body: never;
    response: void;
  };
  "DELETE /api/projects/{projectKey}/environments/{envKey}/keys/{keyId}": {
    params: { keyId: string; projectKey: string; envKey: string };
    body: never;
    response: void;
  };
  "GET /api/projects": {
    params: {};
    body: never;
    response: ProjectResponse[];
  };
  "GET /api/projects/{projectKey}/audit": {
    params: { environment?: string; flag?: string; before?: string; limit?: number; projectKey: string };
    body: never;
    response: AuditPageResponse;
  };
  "GET /api/projects/{projectKey}/environments": {
    params: { projectKey: string };
    body: never;
    response: EnvironmentResponse[];
  };
  "GET /api/projects/{projectKey}/environments/{envKey}/configs": {
    params: { projectKey: string; envKey: string };
    body: never;
    response: FlagConfigResponse[];
  };
  "GET /api/projects/{projectKey}/environments/{envKey}/keys": {
    params: { projectKey: string; envKey: string };
    body: never;
    response: ApiKeyResponse[];
  };
  "GET /api/projects/{projectKey}/flags": {
    params: { projectKey: string };
    body: never;
    response: FlagResponse[];
  };
  "GET /api/projects/{projectKey}/flags/{flagKey}": {
    params: { flagKey: string; projectKey: string };
    body: never;
    response: FlagResponse;
  };
  "GET /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: never;
    response: FlagConfigResponse;
  };
  "GET /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}/overrides": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: never;
    response: OverridesResponse;
  };
  "GET /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}/rules": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: never;
    response: RulesResponse;
  };
  "PATCH /api/projects/{projectKey}/flags/{flagKey}": {
    params: { flagKey: string; projectKey: string };
    body: UpdateFlagRequest;
    response: FlagResponse;
  };
  "PATCH /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: UpdateFlagConfigRequest;
    response: FlagConfigResponse;
  };
  "POST /api/auth/login": {
    params: {};
    body: LoginRequest;
    response: AccessTokenResponse;
  };
  "POST /api/auth/register": {
    params: {};
    body: RegisterRequest;
    response: AccountResponse;
  };
  "POST /api/projects": {
    params: {};
    body: CreateProjectRequest;
    response: ProjectResponse;
  };
  "POST /api/projects/{projectKey}/environments": {
    params: { projectKey: string };
    body: CreateEnvironmentRequest;
    response: EnvironmentResponse;
  };
  "POST /api/projects/{projectKey}/environments/{envKey}/keys": {
    params: { projectKey: string; envKey: string };
    body: IssueApiKeyRequest;
    response: IssuedApiKeyResponse;
  };
  "POST /api/projects/{projectKey}/flags": {
    params: { projectKey: string };
    body: CreateFlagRequest;
    response: FlagResponse;
  };
  "POST /api/projects/{projectKey}/flags/{flagKey}/archive": {
    params: { flagKey: string; projectKey: string };
    body: never;
    response: FlagResponse;
  };
  "POST /api/projects/{projectKey}/flags/{flagKey}/restore": {
    params: { flagKey: string; projectKey: string };
    body: never;
    response: FlagResponse;
  };
  "PUT /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}/overrides": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: ReplaceOverridesRequest;
    response: OverridesResponse;
  };
  "PUT /api/projects/{projectKey}/flags/{flagKey}/config/{envKey}/rules": {
    params: { flagKey: string; projectKey: string; envKey: string };
    body: ReplaceRulesRequest;
    response: RulesResponse;
  };
}
